version: '3.8'

services:
  # PostgreSQL 16 - primary data store for devices, interfaces, links, overrides
  postgres:
    image: postgres:16-alpine
    container_name: unoc-postgres
    environment:
      POSTGRES_USER: unoc            # Change in production
      POSTGRES_PASSWORD: unocpw      # Change in production
      POSTGRES_DB: unocdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U unoc"]
      interval: 5s
      timeout: 5s
      retries: 5

  # FastAPI backend - REST API + provisioning + WebSocket gateway
  backend:
    build: .                         # Uses Dockerfile at repo root
    container_name: unoc-backend
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgresql+asyncpg://unoc:unocpw@postgres:5432/unocdb
    volumes:
      - ./backend:/app/backend       # Mount code for live reload in dev
      - ./run.py:/app/run.py
    depends_on:
      postgres:
        condition: service_healthy
    command: python -m uvicorn backend.main:app --host 0.0.0.0 --port 5001 --reload

volumes:
  postgres_data:
